<?php
/**
 * Created by PhpStorm.
 * User: oleg
 * Date: 06.08.17
 * Time: 15:35
 */


class Cake extends BaseModel{

    protected $cakes;

    public function getData()
    {
        parent::getData(); // TODO: Change the autogenerated stub
    }


}