<?php
/**
 * Created by PhpStorm.
 * User: oleg
 * Date: 06.08.17
 * Time: 15:35
 */
namespace application\models;

use application\core\BaseModel;
use application\core\MyPDO;
class Site extends BaseModel{


    public function getCategories(){
        $data = MyPDO::getData('name','categories');
        foreach ($data as $row){
            $this->categoryName[] = $row['name'];
        }
        return $this->categoryName;
    }

    /**
     * @return string
     */
    public function getCakes()
    {
        $data = MyPDO::getData('*','cakes');
        foreach ($data as $row){
            $this->cakesName[] = $row;
        }
        return $this->cakesName;
    }


    public function getData()
    {
        parent::getData(); // TODO: Change the autogenerated stub
    }


}